import os
from dotenv import load_dotenv

load_dotenv()

PUBLIC_DATA_API_KEY = os.getenv("PUBLIC_DATA_API_KEY", "")

APARTMENTS = {
    "hongje-hanyang": {
        "name": "홍제한양",
        "dong": "홍제동",
        "gu": "서대문구",
        "lawd_cd": "11410",
        "complex_no": "7961",
        "search_names": ["홍제한양", "홍제 한양"],
        "info": {
            "address": "서울시 서대문구 홍제동",
            "totalHouseholdCount": 998,
            "highFloor": "15",
            "useApproveYmd": "1993.05",
            "builder": "(주)한양",
            "areas": "76㎡, 95㎡, 131㎡",
        },
    },
    "hillstate-nokbun": {
        "name": "힐스테이트녹번",
        "dong": "녹번동",
        "gu": "은평구",
        "lawd_cd": "11380",
        "complex_no": "111964",
        "search_names": ["힐스테이트녹번", "힐스테이트 녹번"],
        "hidden_area_types": ["39", "49"],
        "info": {
            "address": "서울시 은평구 녹번동",
            "totalHouseholdCount": 952,
            "highFloor": "",
            "useApproveYmd": "2019.05",
            "builder": "현대엔지니어링(주)",
            "areas": "66~156㎡",
        },
    },
    "hongjewon-hyundai": {
        "name": "홍제원현대",
        "dong": "홍제동",
        "gu": "서대문구",
        "lawd_cd": "11410",
        "complex_no": "26841",
        "search_names": ["홍제원현대", "홍제원 현대"],
        "info": {
            "address": "서울시 서대문구 홍제동",
            "totalHouseholdCount": 939,
            "highFloor": "18",
            "useApproveYmd": "2000.06",
            "builder": "현대건설(주)",
            "areas": "82㎡, 107㎡, 140㎡",
        },
    },
    "bukhansan-desharp": {
        "name": "북한산더샵",
        "dong": "홍은동",
        "gu": "서대문구",
        "lawd_cd": "11410",
        "complex_no": "110458",
        "search_names": ["북한산더샵"],
        "info": {
            "address": "서울시 서대문구 홍은동",
            "totalHouseholdCount": 552,
            "highFloor": "",
            "useApproveYmd": "2017.12",
            "builder": "포스코건설(주)",
            "areas": "59㎡, 84㎡, 114㎡, 120㎡",
        },
    },
    "jegi-hanshin": {
        "name": "제기한신",
        "dong": "제기동",
        "gu": "동대문구",
        "lawd_cd": "11230",
        "complex_no": "3277",
        "search_names": ["한신아파트"],
        "search_dong": "제기동",
        "info": {
            "address": "서울시 동대문구 제기동",
            "totalHouseholdCount": 1070,
            "highFloor": "",
            "useApproveYmd": "2004.05",
            "builder": "한신공영(주)",
            "areas": "59㎡, 84㎡, 114㎡",
        },
    },
    "sinchon-lucky": {
        "name": "신촌럭키",
        "dong": "대현동",
        "gu": "서대문구",
        "lawd_cd": "11410",
        "complex_no": "423",
        "search_names": ["신촌럭키"],
        "info": {
            "address": "서울시 서대문구 대현동",
            "totalHouseholdCount": 855,
            "highFloor": "",
            "useApproveYmd": "1999.02",
            "builder": "럭키개발(주)",
            "areas": "59㎡, 83㎡",
        },
    },
    "bukahyeon-doosan": {
        "name": "북아현두산",
        "dong": "북아현동",
        "gu": "서대문구",
        "lawd_cd": "11410",
        "complex_no": "849",
        "search_names": ["두산"],
        "search_dong": "북아현동",
        "info": {
            "address": "서울시 서대문구 북아현동",
            "totalHouseholdCount": 956,
            "highFloor": "",
            "useApproveYmd": "1999.03",
            "builder": "두산건설(주)",
            "areas": "59㎡",
        },
    },
    "cheongyeon-tturanchae": {
        "name": "천연뜨란채",
        "dong": "천연동",
        "gu": "서대문구",
        "lawd_cd": "11410",
        "complex_no": "11567",
        "search_names": ["천연뜨란채"],
        "info": {
            "address": "서울시 서대문구 천연동",
            "totalHouseholdCount": 1008,
            "highFloor": "",
            "useApproveYmd": "2006.03",
            "builder": "",
            "areas": "55㎡, 57㎡, 75㎡, 84㎡",
        },
    },
    "haengdang-sindonga": {
        "name": "행당신동아",
        "dong": "행당동",
        "gu": "성동구",
        "lawd_cd": "11200",
        "complex_no": "332",
        "search_names": ["신동아"],
        "search_dong": "행당동",
        "search_build_year": "1995",
        "info": {
            "address": "서울시 성동구 행당동",
            "totalHouseholdCount": 636,
            "highFloor": "",
            "useApproveYmd": "1995.05",
            "builder": "신동아건설(주)",
            "areas": "59㎡, 76㎡, 84㎡, 114㎡",
        },
    },
    "yongdu-sindonga": {
        "name": "용두신동아",
        "dong": "용두동",
        "gu": "동대문구",
        "lawd_cd": "11230",
        "complex_no": "338",
        "search_names": ["신동아"],
        "search_dong": "용두동",
        "info": {
            "address": "서울시 동대문구 용두동",
            "totalHouseholdCount": 772,
            "highFloor": "",
            "useApproveYmd": "1994.10",
            "builder": "신동아건설(주)",
            "areas": "49㎡, 58㎡, 84㎡",
        },
    },
    "bukhansan-hillstate1": {
        "name": "북한산힐스테이트1차",
        "dong": "불광동",
        "gu": "은평구",
        "lawd_cd": "11380",
        "complex_no": "24199",
        "search_names": ["북한산힐스테이트1차"],
        "info": {
            "address": "서울시 은평구 불광동",
            "totalHouseholdCount": 603,
            "highFloor": "",
            "useApproveYmd": "2009.07",
            "builder": "현대건설(주)",
            "areas": "59㎡, 84㎡, 114㎡",
        },
    },
    "bukhansan-hometown": {
        "name": "북한산현대홈타운",
        "dong": "불광동",
        "gu": "은평구",
        "lawd_cd": "11380",
        "complex_no": "9239",
        "search_names": ["북한산현대홈타운"],
        "info": {
            "address": "서울시 은평구 불광동",
            "totalHouseholdCount": 662,
            "highFloor": "",
            "useApproveYmd": "2004.05",
            "builder": "현대건설(주)",
            "areas": "59㎡, 84㎡, 114㎡",
        },
    },
    "bukhansan-raemian": {
        "name": "북한산래미안",
        "dong": "불광동",
        "gu": "은평구",
        "lawd_cd": "11380",
        "complex_no": "26427",
        "search_names": ["북한산래미안"],
        "info": {
            "address": "서울시 은평구 불광동",
            "totalHouseholdCount": 782,
            "highFloor": "",
            "useApproveYmd": "2010.08",
            "builder": "삼성물산(주)",
            "areas": "59㎡, 84㎡, 114㎡",
        },
    },
    "wolgye-central-ipark": {
        "name": "월계센트럴아이파크",
        "dong": "월계동",
        "gu": "노원구",
        "lawd_cd": "11350",
        "complex_no": "117590",
        "search_names": ["월계센트럴아이파크"],
        "info": {
            "address": "서울시 노원구 월계동",
            "totalHouseholdCount": 859,
            "highFloor": "",
            "useApproveYmd": "2020.01",
            "builder": "",
            "areas": "59㎡, 84㎡",
        },
    },
    "taereung-harrington": {
        "name": "태릉해링턴플레이스",
        "dong": "공릉동",
        "gu": "노원구",
        "lawd_cd": "11350",
        "complex_no": "125162",
        "search_names": ["태릉해링턴플레이스"],
        "info": {
            "address": "서울시 노원구 공릉동",
            "totalHouseholdCount": 1308,
            "highFloor": "",
            "useApproveYmd": "2022.01",
            "builder": "",
            "areas": "59㎡, 74㎡, 84㎡",
        },
    },
    "nowon-central-prugio": {
        "name": "노원센트럴푸르지오",
        "dong": "상계동",
        "gu": "노원구",
        "lawd_cd": "11350",
        "complex_no": "117873",
        "search_names": ["노원센트럴푸르지오"],
        "info": {
            "address": "서울시 노원구 상계동",
            "totalHouseholdCount": 810,
            "highFloor": "",
            "useApproveYmd": "2021.02",
            "builder": "",
            "areas": "59㎡, 84㎡, 104㎡",
        },
    },
    "sinnae-kumkang": {
        "name": "신내역금강펜테리움",
        "dong": "망우동",
        "gu": "중랑구",
        "lawd_cd": "11260",
        "complex_no": "125357",
        # 줄인 표시명으로는 네이버 검색이 단지를 못 찾음 → 전체 이름으로 검색
        "naver_query": "신내역금강펜테리움센트럴파크",
        "search_names": ["신내역금강펜테리움센트럴파크"],
        "info": {
            "address": "서울시 중랑구 망우동",
            "totalHouseholdCount": 490,
            "highFloor": "",
            "useApproveYmd": "2021.07",
            "builder": "",
            "areas": "79㎡, 84㎡",
        },
    },
    "imun-ipark-xi": {
        "name": "이문아이파크자이",
        "dong": "이문동",
        "gu": "동대문구",
        "lawd_cd": "11230",
        "complex_no": "174562",
        "search_names": ["이문아이파크자이"],
        "info": {
            "address": "서울시 동대문구 이문동",
            "totalHouseholdCount": 4169,
            "highFloor": "",
            "useApproveYmd": "2025.11",
            "builder": "",
            "areas": "59㎡, 84㎡, 102㎡, 139㎡",
        },
    },
    "hwigyeong-skview": {
        "name": "휘경SK뷰",
        "dong": "휘경동",
        "gu": "동대문구",
        "lawd_cd": "11230",
        "complex_no": "112482",
        "search_names": ["휘경SK뷰"],
        "info": {
            "address": "서울시 동대문구 휘경동",
            "totalHouseholdCount": 900,
            "highFloor": "",
            "useApproveYmd": "2019.06",
            "builder": "",
            "areas": "59㎡, 84㎡, 100㎡",
        },
    },
}
