import os
from dotenv import load_dotenv

load_dotenv()

PUBLIC_DATA_API_KEY = os.getenv("PUBLIC_DATA_API_KEY", "")

APARTMENTS = {
    "hongje-hanyang": {
        "name": "홍제한양",
        "dong": "홍제동",
        "gu": "서대문구",
        "lawd_cd": "11410",
        "complex_no": "7961",
        "search_names": ["홍제한양", "홍제 한양"],
        "info": {
            "address": "서울시 서대문구 홍제동",
            "totalHouseholdCount": 998,
            "highFloor": "15",
            "useApproveYmd": "1993.05",
            "builder": "(주)한양",
            "areas": "76㎡, 95㎡, 131㎡",
        },
    },
    "hillstate-nokbun": {
        "name": "힐스테이트녹번",
        "dong": "녹번동",
        "gu": "은평구",
        "lawd_cd": "11380",
        "complex_no": "111964",
        "search_names": ["힐스테이트녹번", "힐스테이트 녹번"],
        "hidden_area_types": ["39", "49"],
        "info": {
            "address": "서울시 은평구 녹번동",
            "totalHouseholdCount": 952,
            "highFloor": "",
            "useApproveYmd": "2019.05",
            "builder": "현대엔지니어링(주)",
            "areas": "66~156㎡",
        },
    },
    "hongjewon-hyundai": {
        "name": "홍제원현대",
        "dong": "홍제동",
        "gu": "서대문구",
        "lawd_cd": "11410",
        "complex_no": "26841",
        "search_names": ["홍제원현대", "홍제원 현대"],
        "info": {
            "address": "서울시 서대문구 홍제동",
            "totalHouseholdCount": 939,
            "highFloor": "18",
            "useApproveYmd": "2000.06",
            "builder": "현대건설(주)",
            "areas": "82㎡, 107㎡, 140㎡",
        },
    },
    "bukhansan-desharp": {
        "name": "북한산더샵",
        "dong": "홍은동",
        "gu": "서대문구",
        "lawd_cd": "11410",
        "complex_no": "110458",
        "search_names": ["북한산더샵"],
        "info": {
            "address": "서울시 서대문구 홍은동",
            "totalHouseholdCount": 552,
            "highFloor": "",
            "useApproveYmd": "2017.12",
            "builder": "포스코건설(주)",
            "areas": "59㎡, 84㎡, 114㎡, 120㎡",
        },
    },
    "jegi-hanshin": {
        "name": "제기한신",
        "dong": "제기동",
        "gu": "동대문구",
        "lawd_cd": "11230",
        "complex_no": "3277",
        "search_names": ["한신아파트"],
        "search_dong": "제기동",
        "info": {
            "address": "서울시 동대문구 제기동",
            "totalHouseholdCount": 1070,
            "highFloor": "",
            "useApproveYmd": "2004.05",
            "builder": "한신공영(주)",
            "areas": "59㎡, 84㎡, 114㎡",
        },
    },
    "sinchon-lucky": {
        "name": "신촌럭키",
        "dong": "대현동",
        "gu": "서대문구",
        "lawd_cd": "11410",
        "complex_no": "423",
        "search_names": ["신촌럭키"],
        "info": {
            "address": "서울시 서대문구 대현동",
            "totalHouseholdCount": 855,
            "highFloor": "",
            "useApproveYmd": "1999.02",
            "builder": "럭키개발(주)",
            "areas": "59㎡, 83㎡",
        },
    },
    "bukahyeon-doosan": {
        "name": "북아현두산",
        "dong": "북아현동",
        "gu": "서대문구",
        "lawd_cd": "11410",
        "complex_no": "849",
        "search_names": ["두산"],
        "search_dong": "북아현동",
        "info": {
            "address": "서울시 서대문구 북아현동",
            "totalHouseholdCount": 956,
            "highFloor": "",
            "useApproveYmd": "1999.03",
            "builder": "두산건설(주)",
            "areas": "59㎡",
        },
    },
    "cheongyeon-tturanchae": {
        "name": "천연뜨란채",
        "dong": "천연동",
        "gu": "서대문구",
        "lawd_cd": "11410",
        "complex_no": "11567",
        "search_names": ["천연뜨란채"],
        "info": {
            "address": "서울시 서대문구 천연동",
            "totalHouseholdCount": 1008,
            "highFloor": "",
            "useApproveYmd": "2006.03",
            "builder": "",
            "areas": "55㎡, 57㎡, 75㎡, 84㎡",
        },
    },
    "haengdang-sindonga": {
        "name": "행당신동아",
        "dong": "행당동",
        "gu": "성동구",
        "lawd_cd": "11200",
        "complex_no": "332",
        "search_names": ["신동아"],
        "search_dong": "행당동",
        "search_build_year": "1995",
        "info": {
            "address": "서울시 성동구 행당동",
            "totalHouseholdCount": 636,
            "highFloor": "",
            "useApproveYmd": "1995.05",
            "builder": "신동아건설(주)",
            "areas": "59㎡, 76㎡, 84㎡, 114㎡",
        },
    },
    "yongdu-sindonga": {
        "name": "용두신동아",
        "dong": "용두동",
        "gu": "동대문구",
        "lawd_cd": "11230",
        "complex_no": "338",
        "search_names": ["신동아"],
        "search_dong": "용두동",
        "info": {
            "address": "서울시 동대문구 용두동",
            "totalHouseholdCount": 772,
            "highFloor": "",
            "useApproveYmd": "1994.10",
            "builder": "신동아건설(주)",
            "areas": "49㎡, 58㎡, 84㎡",
        },
    },
    "bukhansan-hillstate1": {
        "name": "북한산힐스테이트1차",
        "dong": "불광동",
        "gu": "은평구",
        "lawd_cd": "11380",
        "complex_no": "24199",
        "search_names": ["북한산힐스테이트1차"],
        "info": {
            "address": "서울시 은평구 불광동",
            "totalHouseholdCount": 603,
            "highFloor": "",
            "useApproveYmd": "2009.07",
            "builder": "현대건설(주)",
            "areas": "59㎡, 84㎡, 114㎡",
        },
    },
    "bukhansan-hometown": {
        "name": "북한산현대홈타운",
        "dong": "불광동",
        "gu": "은평구",
        "lawd_cd": "11380",
        "complex_no": "9239",
        "search_names": ["북한산현대홈타운"],
        "info": {
            "address": "서울시 은평구 불광동",
            "totalHouseholdCount": 662,
            "highFloor": "",
            "useApproveYmd": "2004.05",
            "builder": "현대건설(주)",
            "areas": "59㎡, 84㎡, 114㎡",
        },
    },
    "bukhansan-raemian": {
        "name": "북한산래미안",
        "dong": "불광동",
        "gu": "은평구",
        "lawd_cd": "11380",
        "complex_no": "26427",
        "search_names": ["북한산래미안"],
        "info": {
            "address": "서울시 은평구 불광동",
            "totalHouseholdCount": 782,
            "highFloor": "",
            "useApproveYmd": "2010.08",
            "builder": "삼성물산(주)",
            "areas": "59㎡, 84㎡, 114㎡",
        },
    },
    "wolgye-central-ipark": {
        "name": "월계센트럴아이파크",
        "dong": "월계동",
        "gu": "노원구",
        "lawd_cd": "11350",
        "complex_no": "117590",
        "search_names": ["월계센트럴아이파크"],
        "info": {
            "address": "서울시 노원구 월계동",
            "totalHouseholdCount": 859,
            "highFloor": "",
            "useApproveYmd": "2020.01",
            "builder": "",
            "areas": "59㎡, 84㎡",
        },
    },
    "taereung-harrington": {
        "name": "태릉해링턴플레이스",
        "dong": "공릉동",
        "gu": "노원구",
        "lawd_cd": "11350",
        "complex_no": "125162",
        "search_names": ["태릉해링턴플레이스"],
        "info": {
            "address": "서울시 노원구 공릉동",
            "totalHouseholdCount": 1308,
            "highFloor": "",
            "useApproveYmd": "2022.01",
            "builder": "",
            "areas": "59㎡, 74㎡, 84㎡",
        },
    },
    "nowon-central-prugio": {
        "name": "노원센트럴푸르지오",
        "dong": "상계동",
        "gu": "노원구",
        "lawd_cd": "11350",
        "complex_no": "117873",
        "search_names": ["노원센트럴푸르지오"],
        "info": {
            "address": "서울시 노원구 상계동",
            "totalHouseholdCount": 810,
            "highFloor": "",
            "useApproveYmd": "2021.02",
            "builder": "",
            "areas": "59㎡, 84㎡, 104㎡",
        },
    },
    "sinnae-kumkang": {
        "name": "신내역금강펜테리움",
        "dong": "망우동",
        "gu": "중랑구",
        "lawd_cd": "11260",
        "complex_no": "125357",
        # 줄인 표시명으로는 네이버 검색이 단지를 못 찾음 → 전체 이름으로 검색
        "naver_query": "신내역금강펜테리움센트럴파크",
        "search_names": ["신내역금강펜테리움센트럴파크"],
        "info": {
            "address": "서울시 중랑구 망우동",
            "totalHouseholdCount": 490,
            "highFloor": "",
            "useApproveYmd": "2021.07",
            "builder": "",
            "areas": "79㎡, 84㎡",
        },
    },
    "imun-ipark-xi": {
        "name": "이문아이파크자이",
        "dong": "이문동",
        "gu": "동대문구",
        "lawd_cd": "11230",
        "complex_no": "174562",
        "search_names": ["이문아이파크자이"],
        "info": {
            "address": "서울시 동대문구 이문동",
            "totalHouseholdCount": 4169,
            "highFloor": "",
            "useApproveYmd": "2025.11",
            "builder": "",
            "areas": "59㎡, 84㎡, 102㎡, 139㎡",
        },
    },
    "hwigyeong-skview": {
        "name": "휘경SK뷰",
        "dong": "휘경동",
        "gu": "동대문구",
        "lawd_cd": "11230",
        "complex_no": "112482",
        "search_names": ["휘경SK뷰"],
        "info": {
            "address": "서울시 동대문구 휘경동",
            "totalHouseholdCount": 900,
            "highFloor": "",
            "useApproveYmd": "2019.06",
            "builder": "",
            "areas": "59㎡, 84㎡, 100㎡",
        },
    },
    "hillstate-medialle": {
        "name": "힐스테이트메디알레",
        "dong": "대조동",
        "gu": "은평구",
        "lawd_cd": "11380",
        "complex_no": "186117",
        "search_names": ["힐스테이트메디알레"],
        "info": {
            "address": "서울시 은평구 대조동",
            "totalHouseholdCount": 2451,
            "highFloor": "",
            "useApproveYmd": "2026.10",  # 입주 예정 (대조1구역 재개발)
            "builder": "현대건설(주)",
            "areas": "51㎡, 59㎡, 74㎡, 84㎡, 114㎡",
        },
    },
    "sintri-1": {
        "name": "신트리1단지",
        "dong": "신정동",
        "gu": "양천구",
        "lawd_cd": "11470",
        "complex_no": "672",
        # 공공 실거래 표기는 "단지" 없이 "신트리1" → 매칭 키도 그렇게
        "search_names": ["신트리1"],
        "search_dong": "신정동",
        "info": {
            "address": "서울시 양천구 신정동",
            "totalHouseholdCount": 997,
            "highFloor": "",
            "useApproveYmd": "1999.05",
            "builder": "",
            "areas": "49㎡, 59㎡",
        },
    },
    "sintri-4": {
        "name": "신트리4단지",
        "dong": "신정동",
        "gu": "양천구",
        "lawd_cd": "11470",
        "complex_no": "3444",
        "search_names": ["신트리4"],  # 공공 실거래 표기
        "search_dong": "신정동",
        "info": {
            "address": "서울시 양천구 신정동",
            "totalHouseholdCount": 858,
            "highFloor": "",
            "useApproveYmd": "2000.05",
            "builder": "",
            "areas": "49㎡, 59㎡",
        },
    },
    "hakmaeul-1": {
        "name": "학마을1단지",
        "dong": "신정동",
        "gu": "양천구",
        "lawd_cd": "11470",
        "complex_no": "3784",
        "search_names": ["학마을1단지"],
        "search_dong": "신정동",
        "info": {
            "address": "서울시 양천구 신정동",
            "totalHouseholdCount": 639,
            "highFloor": "",
            "useApproveYmd": "2000.10",
            "builder": "",
            "areas": "49㎡, 59㎡",
        },
    },
    "sinjeong-hyundai6": {
        "name": "신정현대6차",
        "dong": "신정동",
        "gu": "양천구",
        "lawd_cd": "11470",
        "complex_no": "3783",
        # 네이버 표시명은 "신정현대6차"지만 공공 실거래 표기는 "신정6현대"
        "search_names": ["신정6현대"],
        "search_dong": "신정동",
        "info": {
            "address": "서울시 양천구 신정동",
            "totalHouseholdCount": 703,
            "highFloor": "",
            "useApproveYmd": "2000.10",
            "builder": "현대산업개발(주)",
            "areas": "59㎡, 84㎡, 114㎡",
        },
    },
    "byeoksan-blooming-1": {
        "name": "벽산블루밍1단지",
        "dong": "신월동",  # 신정동이 아니라 신월동
        "gu": "양천구",
        "lawd_cd": "11470",
        "complex_no": "100390",
        # 전국 동명단지가 많아 양천구로 좁혀 검색 → complexCode 필터로 단지 확정
        "naver_query": "양천구벽산블루밍",
        # "벽산블루밍1단지"는 "양천벽산블루밍1단지"(2006)에도 부분일치 →
        # 준공연도(2003)로 구분
        "search_names": ["벽산블루밍1단지"],
        "search_dong": "신월동",
        "search_build_year": "2003",
        "info": {
            "address": "서울시 양천구 신월동",
            "totalHouseholdCount": 207,
            "highFloor": "",
            "useApproveYmd": "2003.12",
            "builder": "벽산건설(주)",
            "areas": "59㎡, 84㎡",
        },
    },
    "mokdong-central-ipark-weve": {
        "name": "목동센트럴아이파크위브",
        "dong": "신월동",  # 신정뉴타운 생활권이나 법정동은 신월동
        "gu": "양천구",
        "lawd_cd": "11470",
        "complex_no": "117329",
        # 네이버는 1~4단지를 단일 단지(117329)로 등록. RTMS는 단지별로
        # "목동센트럴아이파크위브1~4단지"로 나뉘므로 공통 접두어로 전체 매칭.
        "search_names": ["목동센트럴아이파크위브"],
        "search_dong": "신월동",
        "info": {
            "address": "서울시 양천구 신월동",
            "totalHouseholdCount": 3045,
            "highFloor": "",
            "useApproveYmd": "2020.05",
            "builder": "HDC현대산업개발·두산건설",
            "areas": "52㎡, 59㎡, 84㎡",
        },
    },
    "yeomchang-donga-3": {
        "name": "염창동아3차",  # 네이버 표시명 (사용자 표기 '염창동동아3차'와 동일 단지)
        "dong": "염창동",
        "gu": "강서구",
        "lawd_cd": "11500",
        "complex_no": "870",
        # RTMS 실거래 표기는 "동아3" (염창동 한정, "동아"·"한강동아"와 구분됨)
        "search_names": ["동아3"],
        "search_dong": "염창동",
        "info": {
            "address": "서울시 강서구 염창동",
            "totalHouseholdCount": 570,
            "highFloor": "",
            "useApproveYmd": "1999.01",
            "builder": "동아건설(주)",
            "areas": "59㎡, 84㎡",
        },
    },
    "sinjeong-newtown-lotte-castle": {
        "name": "신정뉴타운롯데캐슬",
        "dong": "신월동",  # 신정뉴타운이나 법정동은 신월동(1063)
        "gu": "양천구",
        "lawd_cd": "11470",
        "complex_no": "107728",
        # RTMS 표기는 단순 "롯데캐슬" → 신월동 내 동명 단지(2010·2008 등)와
        # 준공연도(2014)로 구분
        "search_names": ["롯데캐슬"],
        "search_dong": "신월동",
        "search_build_year": "2014",
        "info": {
            "address": "서울시 양천구 신월동",
            "totalHouseholdCount": 968,
            "highFloor": "",
            "useApproveYmd": "2014.02",
            "builder": "롯데건설(주)",
            "areas": "59㎡, 84㎡, 116㎡, 129㎡",
        },
    },
    "raemian-verahills": {
        "name": "래미안베라힐즈",
        "dong": "녹번동",
        "gu": "은평구",
        "lawd_cd": "11380",
        "complex_no": "111575",
        # RTMS 표기도 "래미안베라힐즈"로 동일·유니크 (북한산래미안 등과 구분됨)
        "search_names": ["래미안베라힐즈"],
        "search_dong": "녹번동",
        "info": {
            "address": "서울시 은평구 녹번동",
            "totalHouseholdCount": 1305,
            "highFloor": "",
            "useApproveYmd": "2019.08",
            "builder": "삼성물산(주)",
            "areas": "59㎡, 84㎡, 114㎡",
        },
    },
    "daechi-seonkyung-3": {
        "name": "대치선경3차",
        "dong": "대치동",
        "gu": "강남구",
        "lawd_cd": "11680",
        "complex_no": "9005",
        # 대치동에 선경1·2·3차가 모두 있음. RTMS "선경3차"(1990)만 매칭
        # ("선경1차(1동-7동)"·"선경2차(8동-12동)"와 구분)
        "search_names": ["선경3차"],
        "search_dong": "대치동",
        "info": {
            "address": "서울시 강남구 대치동",
            "totalHouseholdCount": 54,
            "highFloor": "",
            "useApproveYmd": "1990.10",
            "builder": "선경건설(주)",
            "areas": "76㎡",
        },
    },
    "tenzhill-2": {
        "name": "텐즈힐2단지",
        "dong": "상왕십리동",  # 1단지는 하왕십리동 → 동으로도 구분됨
        "gu": "성동구",
        "lawd_cd": "11200",
        "complex_no": "104190",
        # RTMS 표기 "텐즈힐(2단지)" (괄호 포함). 1단지와 구분
        "search_names": ["텐즈힐(2단지)"],
        "search_dong": "상왕십리동",
        "info": {
            "address": "서울시 성동구 상왕십리동",
            "totalHouseholdCount": 1148,
            "highFloor": "",
            "useApproveYmd": "2014.06",
            "builder": "GS건설·현대산업개발·삼성물산·대림산업",
            "areas": "55㎡, 59㎡, 84㎡, 127㎡, 157㎡",
        },
    },
    "gwanak-dreamtown": {
        "name": "관악드림타운",
        "dong": "봉천동",
        "gu": "관악구",
        "lawd_cd": "11620",
        "complex_no": "2987",
        # 네이버는 통합 단지(2987). RTMS는 "관악드림(동아)"·"관악드림(삼성)"
        # 2개로 나뉘므로 공통 접두어 "관악드림"으로 전체 매칭
        "search_names": ["관악드림"],
        "search_dong": "봉천동",
        "info": {
            "address": "서울시 관악구 봉천동",
            "totalHouseholdCount": 3544,
            "highFloor": "",
            "useApproveYmd": "2003.09",
            "builder": "삼성물산·동아건설산업",
            "areas": "59㎡, 84㎡, 102㎡, 114㎡",
        },
    },
}
